title: Análisis Matemático II
description: Resolución y apuntes para Análisis Matemático 2 - FIUBA 2025 1C
show_downloads: false

baseurl: "/analisis-matematico-ii" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://ianchu0317.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: ianchuu
image: /thumbnail-jumbo.png
twitter:
  username: 

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
